const people=[{name:'The Burden',rarity:'COMMON · 1,500 TOTAL',lore:'It went looking for someone it lost. It came back carrying something that still breathes. It has never put it down.'},{name:'The Listener',rarity:'RARE · 500 TOTAL',lore:'It followed a familiar voice into Room 13. Now the missing speak through it. There is one voice that makes all the others fall silent.'},{name:'The Crawler',rarity:'LEGENDARY · 222 TOTAL',lore:'It saw what waited behind the door. The passage narrowed as it ran. Its body changed to escape. It still looks behind it.'}];
let selected=0;let audioCtx,hum,gain;let soundOn=false;
function openDialog(id){const d=document.getElementById(id);d.showModal();document.body.classList.add('modal-open');if(id==='footage'&&gain)gain.gain.value=0;}
document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>openDialog(b.dataset.open)));
document.querySelectorAll('dialog').forEach(d=>{d.querySelector('.close').onclick=()=>d.close();d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});d.addEventListener('close',()=>{document.body.classList.remove('modal-open');if(d.id==='footage'){d.querySelector('video').pause();if(gain&&soundOn)gain.gain.value=.018;}});});
function choose(index){selected=index;document.querySelectorAll('.character').forEach((b,i)=>{b.classList.toggle('active',i===index);b.setAttribute('aria-pressed',i===index?'true':'false');});const c=people[index];const art=document.getElementById('mintArt');art.src='assets/nft/'+['common','rare','legendary'][index]+'.png';art.alt=c.name+' — full character artwork';document.getElementById('mintName').textContent=c.name;document.getElementById('mintRarity').textContent=c.rarity;document.getElementById('mintLore').textContent=c.lore;document.getElementById('mintPrice').textContent=['0.0004 ETH','0.001 ETH','0.002 ETH'][index];window.dispatchEvent(new Event('selectionchanged'));}
document.querySelectorAll('[data-character]').forEach(b=>b.onclick=()=>{choose(Number(b.dataset.character));openDialog('mint');});choose(0);
document.getElementById('openMint').onclick=()=>openDialog('mint');
document.getElementById('sound').onclick=async()=>{const b=document.getElementById('sound');try{if(!audioCtx){audioCtx=new(window.AudioContext||window.webkitAudioContext)();hum=audioCtx.createOscillator();gain=audioCtx.createGain();hum.frequency.value=53;gain.gain.value=0;hum.connect(gain);gain.connect(audioCtx.destination);hum.start();}await audioCtx.resume();soundOn=!soundOn;gain.gain.setTargetAtTime(soundOn?.018:0,audioCtx.currentTime,.2);b.querySelector('span').textContent=soundOn?'on':'off';b.setAttribute('aria-pressed',String(soundOn));}catch{b.querySelector('span').textContent='unavailable';}};
let knockCount=0,whisperTimer;document.getElementById('door').onclick=()=>{const w=document.getElementById('whisper');knockCount++;w.textContent=knockCount%3===0?'The fourth knock came from behind you.':'Someone is listening.';clearTimeout(whisperTimer);whisperTimer=setTimeout(()=>w.textContent='',3500);};